spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2jwt?serverTimezone=Asia/Seoul&characterEncoding=UTF-8?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 924498
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  mustache:
    servlet:
      expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: uCbxP4O9FloXFOEHjxzG
            client-secret: rDZguwdBhb
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-name: google
            client-id: 367636032624-e3k449cqfvekmrvhcu9ou5dbj5pel1t3.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql : trace
